import{get}from"./api.js";import{draw}from"./world.js";import{agents}from"./agent-panel.js";import{bindReplay}from"./replay.js";
import{trainingPanel}from"./training-panel.js";
let savedReport=null;
document.getElementById("report").addEventListener("change",async event=>{try{savedReport=event.target.value?await get("/api/reports/"+encodeURIComponent(event.target.value)):null;await poll();}catch(error){showError(error);}});
const $=id=>document.getElementById(id);let episode=null,frame=null,following=true,generation=0;
function render(){if(!frame)return;draw($("world"),frame,$("perspective").value);agents($("agents"),frame.observations);$("episode-title").textContent=frame.state.family.replaceAll("_"," ")+" · step "+frame.state.step;$("frame").max=frame.frame_count-1;$("frame").value=frame.state.step;$("frame-label").textContent=frame.state.step;$("frame-info").textContent=(following?($("status").textContent==="collecting"?"Live collection":"Last collected episode"):"Saved replay")+" · "+episode+" · episode checkpoint "+(frame.checkpoint_id||"unknown").slice(0,16);}
async function load(index=-1){if(!episode)return;const current=++generation;const result=await get("/api/frame?episode="+encodeURIComponent(episode)+"&index="+index);if(current===generation){frame=result;render();}}
bindReplay($("frame"),index=>{following=false;load(index).catch(showError);});$("perspective").addEventListener("change",render);$("live").addEventListener("click",()=>{following=true;poll();});
function showError(error){$("connection").textContent="Disconnected · retrying";$("reason").textContent=error.message;}
async function poll(){try{const state=await get("/api/status"),run=state.run;$("connection").textContent="Connected";$("status").textContent=run.status;$("reason").textContent=run.reason||(run.run_id?"Run "+run.run_id+" · "+run.status:"No run has started. Start a bounded run through the controller API.");$("metrics").replaceChildren();const latest=(run.metrics||[]).at(-1)||{};for(const [label,value]of [["Completed updates",run.cycles||0],["Checkpoint",(run.checkpoint_id||"none").slice(0,16)],["Last loss",latest.loss??"—"],["Router overflow",latest.overflow??"—"]]){const dt=document.createElement("dt"),dd=document.createElement("dd");dt.textContent=label;dd.textContent=typeof value==="number"?value.toFixed(3):value;$("metrics").append(dt,dd);}
$("episodes").replaceChildren();for(const row of(run.episodes||[]).slice(-8).reverse()){const button=document.createElement("button");button.textContent=row.family+" · "+(row.success?"success":"unfinished objective")+" · "+row.steps+" steps";button.onclick=()=>{following=false;episode=row.episode_id;load().catch(showError);};$("episodes").append(button);}
trainingPanel($("training-panel"),savedReport||run);const reports=await get("/api/reports");for(const report of reports.reports){if(!Array.from($("report").options).some(o=>o.value===report.run_id)){const option=document.createElement("option");option.value=report.run_id;option.textContent=report.run_id.slice(0,12);$("report").append(option);}}
if(following&&state.live){episode=state.live.episode_id;await load();}}catch(error){showError(error);}}
async function loop(){await poll();setTimeout(loop,1500);}loop();
