export function trainingPanel(root,run){root.replaceChildren();const title=document.createElement("p");title.textContent="Run "+(run.run_id||"not started")+" · "+run.status;root.append(title);const metrics=run.metrics||[];
if(metrics.length){const canvas=document.createElement("canvas");canvas.width=900;canvas.height=220;canvas.setAttribute("aria-label","Learning loss by completed update");root.append(canvas);const ctx=canvas.getContext("2d");const values=metrics.map(m=>m.loss).filter(Number.isFinite);if(values.length){let low=Math.min(...values),high=Math.max(...values);if(low===high){low-=.5;high+=.5;}ctx.strokeStyle="#4a6371";ctx.beginPath();ctx.moveTo(50,20);ctx.lineTo(50,180);ctx.lineTo(870,180);ctx.stroke();ctx.fillStyle="#b5c6ce";ctx.font="13px system-ui";ctx.fillText(high.toFixed(3),0,25);ctx.fillText(low.toFixed(3),0,180);ctx.fillText("Completed updates",370,212);ctx.strokeStyle="#82d2b3";ctx.beginPath();values.forEach((v,i)=>{const x=50+i*810/Math.max(1,values.length-1),y=180-(v-low)*155/(high-low);if(i)ctx.lineTo(x,y);else ctx.moveTo(x,y);});ctx.stroke();ctx.fillStyle="#82d2b3";values.forEach((v,i)=>{ctx.beginPath();ctx.arc(50+i*810/Math.max(1,values.length-1),180-(v-low)*155/(high-low),4,0,Math.PI*2);ctx.fill();});}const text=document.createElement("p");text.textContent=metrics.length+" recorded updates · latest loss "+Number(metrics.at(-1).loss).toFixed(4)+". Loss alone does not measure teamwork.";root.append(text);}
const latest=metrics.at(-1)||{};const routing=Object.entries(latest).filter(([key])=>/^router_layer_\d+_overflow$/.test(key));if(routing.length){const p=document.createElement("p");p.textContent="Expert capacity drops by layer: "+routing.map(([key,value])=>key.split("_")[2]+": "+(value*100).toFixed(1)+"%").join(" · ");root.append(p);}
if(Number.isFinite(latest.approx_kl)){const p=document.createElement("p");p.textContent="During update: approximate KL "+latest.approx_kl.toFixed(4)+" · clipping fraction "+(latest.clip_fraction*100).toFixed(1)+"% · "+latest.diagnostic_samples+" sample presentations. Averaged before each optimizer step; not a final-policy comparison.";root.append(p);}
for(const family of ["switch_delivery","clue_search"]){const episodes=(run.episodes||[]).filter(e=>e.family===family&&["train","practice"].includes(e.split)&&e.diagnostics);if(!episodes.length)continue;const totals={actions:0,blocked:0,ineffective:0,plate:0,parcel:0,complete:0};for(const e of episodes){const d=e.diagnostics;totals.actions+=d.agent_actions;totals.blocked+=(d.results.blocked||0)+(d.results.collision||0);for(const key of ["nothing_to_pick_up","nothing_to_drop","nothing_to_interact"])totals.ineffective+=d.results[key]||0;totals.plate+=!!d.subgoals.plate_held;totals.parcel+=!!d.subgoals.object_collected;totals.complete+=!!d.objective_completed;}const p=document.createElement("p");p.textContent=family.replaceAll("_"," ")+" · "+episodes.length+" retained training/practice episodes with diagnostics · "+totals.actions+" agent actions · blocked/collided "+totals.blocked+" · ineffective interactions "+totals.ineffective+" · objective completed "+totals.complete+"/"+episodes.length+(family==="switch_delivery"?" · plate reached "+totals.plate+" · parcel collected "+totals.parcel:"");root.append(p);}
const history=run.resource_history||[];if(history.length){const p=document.createElement("p");const last=history.at(-1);p.textContent="Stored data across services: "+(last.bytes/1024**3).toFixed(2)+" GiB · smallest free reserve "+(last.free_bytes/1024**3).toFixed(1)+" GiB · "+history.length+" resource samples.";root.append(p);}
const rewards={};for(const episode of run.episodes||[])for(const[key,value]of Object.entries(episode.reward_components||{}))rewards[key]=(rewards[key]||0)+value;if(Object.keys(rewards).length){const p=document.createElement("p");p.textContent="Reward components (retained episodes): "+Object.entries(rewards).map(([key,value])=>key+" "+value.toFixed(3)).join(" · ");root.append(p);}
const evaluation=run.evaluation||[];for(const batch of evaluation.slice(-5)){const p=document.createElement("p");p.textContent=batch.split+(batch.complete===false?" — INCOMPLETE":"")+": "+Object.entries(batch.results||{}).map(([name,result])=>name.replaceAll("_"," ")+" "+result.wins+"/"+result.episodes+" ("+(result.success_rate*100).toFixed(1)+"%; 95% interval "+(result.interval95||[]).map(v=>(v*100).toFixed(1)+"%").join("–")+")").join(" · ");root.append(p);if(batch.complete===false){const reason=document.createElement("p");reason.textContent=batch.reason||"Incomplete batches cannot advance curriculum or mastery.";root.append(reason);}}
if(!evaluation.length){const p=document.createElement("p");p.textContent="No completed evaluation batches in this report.";root.append(p);}if(run.reason){const p=document.createElement("p");p.textContent=run.reason;root.append(p);}}
